#!/bin/bash

isset() {

  if [ -z $1 ]
  then

    echo "Environment variable $2 must be set !";
    exit 1;

  fi

}

check_conf() {

  isset $PORT "PORT" 
  isset $DB_HOST "DB_HOST"
  isset $DB_USER "DB_USER"
  isset $DB_PASS "DB_PASS"
  isset $DB_NAME "DB_NAME"
  isset $URL "URL"

}

install() {

  pushd www-ghost

  ghost install \
  --no-prompt \
  --no-stack \
  --no-start \
  --no-setup-mysql \
  --no-setup-nginx \
  --no-setup-systemd \
  --no-setup-linux-user \
  --no-check-mem \
  --port $PORT \
  --dbhost $DB_HOST \
  --dbuser $DB_USER \
  --dbpass $DB_PASS \
  --dbname $DB_NAME \
  --url $URL

  if [ -e ../www-ghost-additions/config.production.json ]
  then

    ../www-ghost-additions/jq -s add config.production.json \
      ../www-ghost-additions/config.production.json 

    rm -R ../www-ghost-additions/config.production.json

  fi
  
  cp -R ../www-ghost-additions/* .

  popd

}

write_extra_configs() {

  local host=${HOST:-'0.0.0.0'}
  local port=${DB_PORT:-3306}

  pushd www-ghost

  ghost config 'server.host' "$host"
  ghost config 'database.connection.port' "$port"

  popd

}

copy_theme() {

  mv /tmp/app-theme www-ghost/content/themes

}

start_ghost() {

  cd www-ghost

  node current/index.js

}

main () {
  
  check_conf
  install
  write_extra_configs
  copy_theme
  start_ghost

}

main
